import { Category, Business, WorkingHours } from './types';

// Admin credentials (for demo purposes)
export const ADMIN_PASSWORD = 'admin123';

// Categories with icons - Education focused
export const CATEGORIES: Category[] = [
    {
        id: 'kindergartens',
        name: 'Kindergartens',
        icon: '👶',
        description: 'Kindergartens and early childhood education centers',
        count: 0,
    },
    {
        id: 'preschools',
        name: 'Preschools',
        icon: '🎨',
        description: 'Preschools and nursery schools for young children',
        count: 0,
    },
    {
        id: 'primary-schools',
        name: 'Primary Schools',
        icon: '🎓',
        description: 'Primary and elementary schools (Classes 1-5)',
        count: 0,
    },
    {
        id: 'secondary-schools',
        name: 'Secondary Schools',
        icon: '🏫',
        description: 'Secondary and high schools (Classes 6-12)',
        count: 0,
    },
    {
        id: 'montessori',
        name: 'Montessori Schools',
        icon: '🌱',
        description: 'Montessori method-based educational institutions',
        count: 0,
    },
    {
        id: 'playschools',
        name: 'Playschools',
        icon: '🧸',
        description: 'Play-based learning centers for toddlers',
        count: 0,
    },
    {
        id: 'tutoring',
        name: 'Tutoring Centers',
        icon: '👨‍🏫',
        description: 'Private tutoring and coaching centers',
        count: 0,
    },
    {
        id: 'international-schools',
        name: 'International Schools',
        icon: '🌍',
        description: 'International curriculum schools (IB, IGCSE)',
        count: 0,
    },
    {
        id: 'cbse-schools',
        name: 'CBSE Schools',
        icon: '📚',
        description: 'CBSE affiliated schools',
        count: 0,
    },
    {
        id: 'icse-schools',
        name: 'ICSE Schools',
        icon: '📖',
        description: 'ICSE and ISC affiliated schools',
        count: 0,
    },
    {
        id: 'state-board',
        name: 'State Board Schools',
        icon: '🏛️',
        description: 'State board affiliated schools',
        count: 0,
    },
    {
        id: 'special-education',
        name: 'Special Education',
        icon: '🌟',
        description: 'Schools for children with special needs',
        count: 0,
    },
    {
        id: 'daycare',
        name: 'Daycare Centers',
        icon: '👼',
        description: 'Daycare and childcare facilities',
        count: 0,
    },
    {
        id: 'skill-development',
        name: 'Skill Development',
        icon: '🎯',
        description: 'Skill development and vocational training centers',
        count: 0,
    },
    {
        id: 'language-schools',
        name: 'Language Schools',
        icon: '🗣️',
        description: 'Language learning and communication schools',
        count: 0,
    },
    {
        id: 'art-music',
        name: 'Art & Music Schools',
        icon: '🎵',
        description: 'Art, music, and creative learning centers',
        count: 0,
    },
];

// Default school timings template
export const DEFAULT_WORKING_HOURS: WorkingHours[] = [
    { day: 'Monday', open: '08:00', close: '17:00', isClosed: false },
    { day: 'Tuesday', open: '08:00', close: '17:00', isClosed: false },
    { day: 'Wednesday', open: '08:00', close: '17:00', isClosed: false },
    { day: 'Thursday', open: '08:00', close: '17:00', isClosed: false },
    { day: 'Friday', open: '08:00', close: '17:00', isClosed: false },
    { day: 'Saturday', open: '08:00', close: '13:00', isClosed: false },
    { day: 'Sunday', open: '00:00', close: '00:00', isClosed: true },
];

// Fee range options for schools
export const PRICE_RANGES = [
    { value: '$', label: 'Budget Friendly (< ₹50,000/year)' },
    { value: '$$', label: 'Moderate (₹50,000 - ₹1,00,000/year)' },
    { value: '$$$', label: 'Premium (₹1,00,000 - ₹2,50,000/year)' },
    { value: '$$$$', label: 'Elite (> ₹2,50,000/year)' },
];

// Sample schools for demo - Based on provided kindergarten data
export const SAMPLE_BUSINESSES: Business[] = [
    {
        id: '1',
        name: 'Abigail Hawks Kindergarten',
        category: 'kindergartens',
        description: 'Quality kindergarten education in Sittiya, Governorate Capital. Dedicated to early childhood development with experienced staff.',
        phone: '39470753',
        email: 'abigailhawks@hotmail.co.uk',
        address: 'Building: 1415, Road: 2829, Block: 428, Avear SITTIYA, Governorate: CAPITAL',
        location: {
            latitude: 26.2285,
            longitude: 50.5860,
            city: 'Sittiya',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: true,
        verified: true,
        rating: 4.5,
        reviewCount: 42,
        createdAt: new Date().toISOString(),
        viewCount: 320,
    },
    {
        id: '2',
        name: 'Al Doha Kindergarten',
        category: 'kindergartens',
        description: 'Located in Hamad Town, providing excellent early education with a focus on child development and learning.',
        phone: '17253501',
        email: 'info@aldoha-kgmail.com',
        address: 'Building: 1516, Road: 821, Block: 708, Avear HAMAD, TOWN, Governorate: NORTHERN',
        location: {
            latitude: 26.1148,
            longitude: 50.5080,
            city: 'Hamad Town',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: true,
        verified: true,
        rating: 4.6,
        reviewCount: 58,
        createdAt: new Date().toISOString(),
        viewCount: 445,
    },
    {
        id: '3',
        name: 'Al Semat Kindergarten',
        category: 'kindergartens',
        description: 'Northern Governorate kindergarten committed to nurturing young minds with quality education and care.',
        phone: '17699693',
        email: 'sg-mai@hotmail.com',
        address: 'Building: 1877, Road: 4063, Block: 540, Avear NORTH, Governorate: NORTHERN',
        location: {
            latitude: 26.1500,
            longitude: 50.4800,
            city: 'North',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$',
        featured: false,
        verified: true,
        rating: 4.3,
        reviewCount: 35,
        createdAt: new Date().toISOString(),
        viewCount: 210,
    },
    {
        id: '4',
        name: 'Ayman Montessori Preschool',
        category: 'montessori',
        description: 'Montessori-based preschool in Hamad Town focusing on child-centered learning and development.',
        phone: '17615144',
        email: 'ayman@hotmail.com',
        address: 'Villa 1407 Road 820 Avear HAMAD, TOWN, Governorate: NORTHERN',
        location: {
            latitude: 26.1200,
            longitude: 50.5100,
            city: 'Hamad Town',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: false,
        verified: true,
        rating: 4.7,
        reviewCount: 67,
        createdAt: new Date().toISOString(),
        viewCount: 389,
    },
    {
        id: '5',
        name: 'Al Ahad Kindergarten Home',
        category: 'kindergartens',
        description: 'Home-based kindergarten in Rifaa providing personalized care and early education in a nurturing environment.',
        phone: '17774875',
        email: 'alshahdkn@gmail.com',
        address: 'Building: 7 /9, Road: 7493, Block: 1079, Avear: RIFAA, Governorate: SOUTHERN',
        location: {
            latitude: 26.1296,
            longitude: 50.5550,
            city: 'Rifaa',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$',
        featured: false,
        verified: true,
        rating: 4.2,
        reviewCount: 28,
        createdAt: new Date().toISOString(),
        viewCount: 156,
    },
    {
        id: '6',
        name: 'Al Anza Kindergarten',
        category: 'kindergartens',
        description: 'Quality kindergarten education in North Governorate with experienced teachers and modern facilities.',
        phone: '17071980',
        email: 'kindergarden.alanza@gmail.com',
        address: 'Building: 1 / 9, Road: 616, Block: 610, Avear: NORTH, Governorate: NORTHERN',
        location: {
            latitude: 26.1600,
            longitude: 50.4900,
            city: 'North',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: true,
        verified: true,
        rating: 4.4,
        reviewCount: 51,
        createdAt: new Date().toISOString(),
        viewCount: 278,
    },
    {
        id: '7',
        name: 'Al Asmil Kindergarten',
        category: 'kindergartens',
        description: 'Central location kindergarten dedicated to providing quality early childhood education with caring staff.',
        phone: '17155304',
        email: 'alasmiikindergarten@gmail.com',
        address: 'Building: 3059, Road: 4345, Block: 343, Avear: CENTRAL, Governorate: CAPITAL',
        location: {
            latitude: 26.2235,
            longitude: 50.5814,
            city: 'Central',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: false,
        verified: true,
        rating: 4.5,
        reviewCount: 44,
        createdAt: new Date().toISOString(),
        viewCount: 295,
    },
    {
        id: '8',
        name: 'Al Barsha Kindergarten (Hamad Town)',
        category: 'kindergartens',
        description: 'Established kindergarten in Hamad Town with a strong reputation for quality education and child care.',
        phone: '17431200',
        email: 'kinderaartental@gmail.com',
        address: 'Building: 1874, Road: 837, Block: 709, Avear: HAMAD, TOWN, Governorate: NORTHERN',
        location: {
            latitude: 26.1180,
            longitude: 50.5120,
            city: 'Hamad Town',
        },
        images: [],
        workingHours: DEFAULT_WORKING_HOURS,
        priceRange: '$$',
        featured: true,
        verified: true,
        rating: 4.8,
        reviewCount: 73,
        createdAt: new Date().toISOString(),
        viewCount: 512,
    },
];

// FAQ Data - Education focused
export const FAQ_DATA = [
    {
        category: 'General',
        questions: [
            {
                question: 'How do I search for schools and kindergartens?',
                answer: 'Use the search bar on the homepage to search by school name, category, or location. You can also browse by categories like kindergartens, preschools, or primary schools, and use advanced filters.',
            },
            {
                question: 'Is the service free to use?',
                answer: 'Yes, our education guide directory is completely free for parents and guardians to search and explore educational institutions.',
            },
            {
                question: 'How can I find schools near me?',
                answer: 'Enter your location (city or area) in the location search field, and we will show you all nearby schools and kindergartens. You can also filter by category and ratings.',
            },
        ],
    },
    {
        category: 'For School Administrators',
        questions: [
            {
                question: 'How can I list my school or kindergarten?',
                answer: 'Contact our admin team through the contact form, and we will help you get your educational institution listed on our platform.',
            },
            {
                question: 'Can I update my school information?',
                answer: 'Yes, reach out to our support team with your school details and required changes, and we will update the information promptly.',
            },
            {
                question: 'What information should I provide for listing?',
                answer: 'Please provide your school name, contact details, address, curriculum type, fee structure, facilities, and any other relevant information about your institution.',
            },
        ],
    },
];
